name: submission_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:

  # 01. BRABUS 800 XLP SUPERBLACK
    #Main
    - image/01. BRABUS 800 XLP SUPERBLACK/Main/BRABUSXLPSB001.jpg
    - image/01. BRABUS 800 XLP SUPERBLACK/Main/BRABUSXLPSB002.jpg
    - image/01. BRABUS 800 XLP SUPERBLACK/Main/BRABUSXLPSB003.jpg
    - image/01. BRABUS 800 XLP SUPERBLACK/Main/BRABUSXLPSB004.jpg
    - image/01. BRABUS 800 XLP SUPERBLACK/Main/BRABUSXLPSB005.jpg
    #interior
    - image/01. BRABUS 800 XLP SUPERBLACK/Interior/_BRA0440-1170x780.jpg
    - image/01. BRABUS 800 XLP SUPERBLACK/Interior/_BRA0444-1170x780.jpg
    - image/01. BRABUS 800 XLP SUPERBLACK/Interior/_BRA0500-1170x780.jpg
    - image/01. BRABUS 800 XLP SUPERBLACK/Interior/_BRA0536-1170x780.jpg
    - image/01. BRABUS 800 XLP SUPERBLACK/Interior/_BRA0547-1170x780.jpg

  # 02. BRABUS 900 Mercedes - AMG E 63 S
    #Main
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Main/BRABUS900E001.jpg
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Main/BRABUS900E002.jpg
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Main/BRABUS900E003.jpg
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Main/BRABUS900E004.jpg
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Main/BRABUS900E005.jpg
    #interior
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Interior/_BRA9278-1170x780.jpg
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Interior/_BRA9281-1170x780.jpg
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Interior/_BRA9288-1170x780.jpg
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Interior/_BRA9294-1170x780.jpg
    - image/02. BRABUS 900 Mercedes-AMG E 63 S/Interior/_DSC3447-1170x780.jpg

  # 03. BRABUS 550 ADVENTURE
    #Main
    - image/03. BRABUS 550 ADVENTURE/Main/BRABUS5001.jpg
    - image/03. BRABUS 550 ADVENTURE/Main/BRABUS5002.jpg
    - image/03. BRABUS 550 ADVENTURE/Main/BRABUS5003.jpg
    - image/03. BRABUS 550 ADVENTURE/Main/BRABUS5004.jpg
    #interior
    - image/03. BRABUS 550 ADVENTURE/Interior/C4S_292 (32)-1169x780.jpg
    - image/03. BRABUS 550 ADVENTURE/Interior/C4S_292 (34)-1169x780.jpg
    - image/03. BRABUS 550 ADVENTURE/Interior/C4S_292 (35)-1169x780.jpg
    - image/03. BRABUS 550 ADVENTURE/Interior/C4S_292 (38)-1169x780.jpg

  # 04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION
    #Main
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Main/INVICTO_01.jpg
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Main/INVICTO_02.jpg
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Main/INVICTO_03.jpg
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Main/INVICTO_04.jpg
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Main/INVICTO_05.jpg
    #interior
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Interior/INVICTO_mission (18)-1169x780.jpg
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Interior/INVICTO_mission (19)-1169x780.jpg
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Interior/INVICTO_mission (22)-1169x780.jpg
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Interior/INVICTO_mission (30)-1169x780.jpg
    - image/04. INVICTO MISSION VR6 PLUS ERV FULLY CERTIFIED ARMOURED VEHICLE WITH BLAST PROTECTION/Interior/INVICTO_mission (44)-1169x780.jpg

  # 05. BRABUS 900 ROCKET EDITION GLE 63 S
    #Main
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Main/001-2560x1813.jpg
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Main/003.jpg
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Main/004.jpg
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Main/005.jpg
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/GLE001.jpg
     #interior
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Interior/_BRA0364-1170x780.jpg
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Interior/_BRA0393-1170x780.jpg
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Interior/_BRA0413-1170x780.jpg
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Interior/_BRA0424-1170x780.jpg
    - image/05. BRABUS 900 ROCKET EDITION GLE 63 S/Interior/_BRA0436-1170x780.jpg

  # 06. BRABUS 800 Coupe S 63 COUPÉ
    #Main
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Main/coupe001.jpg
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Main/_BRA0774.NEF0,5x.jpg
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Main/_BRA0776.NEF0,5x.jpg
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Main/_BRA0778.NEF0,5x.jpg
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Main/_BRA0785.NEF0,5x.jpg
    #interior
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Interior/_BRA0794.NEF0,5x-1170x780.jpg
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Interior/_BRA0823.NEF0,5x-1170x780.jpg
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Interior/_BRA0824.NEF0,5x-1170x780.jpg
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Interior/_BRA0828.NEF0,5x-1170x780.jpg
    - image/06. BRABUS 800 Coupe S 63 COUPÉ/Interior/_BRA0829.NEF0,5x-1170x780.jpg

  # 07. BRABUS 800 BLACK & GOLD EDITION
    #Main
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Main/GOLD001.jpg
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Main/C4S_029 (50).jpg
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Main/C4S_029 (52).jpg
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Main/C4S_029 (54).jpg
    #interior
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Interior/C4S_029 (38)-1169x780.jpg
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Interior/C4S_029 (40)-1169x780.jpg
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Interior/C4S_029 (43)-1168x780.jpg
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Interior/C4S_029 (42)-1169x780.jpg
    - image/07. BRABUS 800 BLACK & GOLD EDITION/Interior/C4S_029 (45)-1169x780.jpg


  # 08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63
    #Main
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Main/xlp001.jpg
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Main/C4S_347 (27).jpg
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Main/C4S_347 (43).jpg
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Main/C4S_347 (41).jpg
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Main/C4S_347 (28).jpg
    #interior
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Interior/C4S_347 (2)-1169x780.jpg
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Interior/C4S_347 (5)-1169x780.jpg
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Interior/C4S_347 (10)-1169x780.jpg
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Interior/C4S_347 (7)-1169x780.jpg
    - image/08. BRABUS 800 ADVENTURE XLP - MERCEDES-AMG G 63/Interior/C4S_347 (6)-1169x780.jpg

  # 09. BRABUS ELECTRIC
    #Main
    - image/09. BRABUS ELECTRIC/Main/001.jpg
    - image/09. BRABUS ELECTRIC/Main/BRABUSEQC (29).jpg
    - image/09. BRABUS ELECTRIC/Main/BRABUSEQC (33).jpg
    - image/09. BRABUS ELECTRIC/Main/BRABUSEQC (35).jpg
    #interior
    - image/09. BRABUS ELECTRIC/Interior/_DSC9759-1169x780.jpg
    - image/09. BRABUS ELECTRIC/Interior/BRABUSEQC (20)-1169x780.jpg
    - image/09. BRABUS ELECTRIC/Interior/BRABUSEQC (23)-1169x780.jpg
    - image/09. BRABUS ELECTRIC/Interior/_DSC9761-1169x780.jpg
    - image/09. BRABUS ELECTRIC/Interior/BRABUSEQC (26)-1169x780.jpg

  fonts:
    - family: Rockwell
      fonts:
        - asset: fonts/RockWell Normal.TTF
